// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlx6zJaxNkcQUNBvW_oMNzSMqPTk37bB8',
    appId: '1:1097595944093:web:5777ef10d989a2de646874',
    messagingSenderId: '1097595944093',
    projectId: 'stocktrack-9f089',
    authDomain: 'stocktrack-9f089.firebaseapp.com',
    storageBucket: 'stocktrack-9f089.firebasestorage.app',
    measurementId: 'G-V2B2SY5P67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1L_J0ffCCNr4nSJvljuXX66lDPNeb0Tg',
    appId: '1:1097595944093:android:e5c9c1fa1b715690646874',
    messagingSenderId: '1097595944093',
    projectId: 'stocktrack-9f089',
    storageBucket: 'stocktrack-9f089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDfPwgcF1rsC1kzI-AmhMcObZiyFykug',
    appId: '1:1097595944093:ios:c26061152ffde4d1646874',
    messagingSenderId: '1097595944093',
    projectId: 'stocktrack-9f089',
    storageBucket: 'stocktrack-9f089.firebasestorage.app',
    iosBundleId: 'com.example.stoktrack1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBDfPwgcF1rsC1kzI-AmhMcObZiyFykug',
    appId: '1:1097595944093:ios:c26061152ffde4d1646874',
    messagingSenderId: '1097595944093',
    projectId: 'stocktrack-9f089',
    storageBucket: 'stocktrack-9f089.firebasestorage.app',
    iosBundleId: 'com.example.stoktrack1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlx6zJaxNkcQUNBvW_oMNzSMqPTk37bB8',
    appId: '1:1097595944093:web:24a9f26aa4e7d395646874',
    messagingSenderId: '1097595944093',
    projectId: 'stocktrack-9f089',
    authDomain: 'stocktrack-9f089.firebaseapp.com',
    storageBucket: 'stocktrack-9f089.firebasestorage.app',
    measurementId: 'G-MLJZ7FD10R',
  );
}
